environment:
  mode: 'development'

logging:
  level: 'info'

server:
  port: 4002

db:
  driver: 'pg'
  maxPool: 30
  minPool: 0

api:
  version: 0.0.1
  name: 'v1'

secrets:
  pgPath: '/pg'
  pgType: 'shared'

auth:
  appName = 'Doodlemon'
  apiDomain = 'https://api.doodlemon.lol'
  websiteDomain = 'https://app.doodlemon.lol'
  authBasePath = '/auth/'
